site_name: Roy's Secret Garden

repo_name: Roy-Kid
repo_url: https://github.com/Roy-Kid

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - header.autohide

plugins:
    - awesome-pages:
        filename: .index
        collapse_single_pages: true
        strict: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Roy-Kid
      name: Roy's Github
  generator: false

copyright: Copyright &copy; 2023 Roy Kid

nav:
    - Home: 
      - Welcome: index.md
      - Curriculum Vitae: cv.md

    - ...